# Generated by Django 5.2.3 on 2025-07-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_api', '0002_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('litre', 'Litre'), ('ml', 'Millilitre'), ('pcs', 'Pieces'), ('pack', 'Pack'), ('other', 'Other')], default='pcs', max_length=20),
        ),
    ]
