# Generated by Django 5.2.3 on 2025-07-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_api', '0003_item_quantity_item_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
