# Generated by Django 5.2.3 on 2025-07-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_api', '0005_remove_cartitem_quantity_item_unit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('litre', 'Litre'), ('ml', 'Millilitre'), ('pcs', 'Pieces'), ('pack', 'Pack'), ('dozen', 'Dozen'), ('other', 'Other')], default='pcs', max_length=20),
        ),
    ]
