# Generated by Django 5.2.3 on 2025-09-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_api', '0008_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
